import type { Metadata } from "next";
import { ReduxProviders } from "@/redux/provider";
import "../app/globals.css";
import "flatpickr/dist/flatpickr.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ToastProvider from "./ToastProvider";
import { inter } from "./font";


export const metadata: Metadata = {
  title: "Think Movies, Go Moveek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ReduxProviders>{children}</ReduxProviders>
       <ToastProvider/>
      </body>
    </html>
  );
}
